version: '3'

services:
  capi:
    image: capi:0.1.0
    container_name: capi
    build:
      context: ../../
      dockerfile: ./ci/development/dockerfile
    restart: unless-stopped
    volumes:
      - "../..:/src/capi"
    ports:
      - "8080:8080"
    networks:
      - capi_net

networks:
  capi_net:
    name: capi_net
