version: '3'

services:
  express:
    container_name: mongo_express
    image: mongo-express
    restart: unless-stopped
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      #ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    links:
      - mongodb
    ports:
      - 8071:8081
    networks:
      - capi_net
  
  mongodb:
    container_name: mongo
    image: mongo:7
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - capi_net

networks:
  capi_net:
